name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master,dev/develop]
  pull_request:
    branches: [ master,dev/develop]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-linux-desktop-simulator:
    runs-on: ubuntu-latest
    env:
      buildDir: '${{ github.workspace }}/build'
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install conan
      uses:  BSFishy/pip-action@v1
      with:
        packages: |
          conan
    - name: Intall system required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libegl-dev
    #Install the latest cmake
    - name : Get the latest CMake version
      uses: lukka/get-cmake@latest
    
    - name: Set up GCC 11
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 11
        platform: x64

    - name: Build the image
      run: |
        REPO_ROOT=${{ github.workspace }}
        make BR2_EXTERNAL=${REPO_ROOT} -C buildroot O=${REPO_ROOT}/image_build/ orange_table_defconfig



